---
title       : Revenue Streams for Musicians / Artists from Digital Media Distribution & Live Performance
subtitle    : Analyses for Independent Musicians / Artists
author      : B.A. McDougall
job         : NSCI Consulting
framework   : io2012     # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : [mathjax, bootstrap]            # {mathjax, quiz, bootstrap}
ext_widgets: {rCharts: [libraries/nvd3, libraries/leaflet]}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Outline
* Market Size of US Music Industry 2015
* Competitive Landscape of Recording Labels
* Profile of American Music Consumer 2015
* Income Profile of Musicians
* Work Profile of Musicians
* Benefits of Streaming Music for Musicians
* Platforms for Distribution of Digital Music
* Summary
* Strategic Plan
* Final Conclusions & Survey

---

## Market Size of US Music Industry 2015
* [Recording Industry Association of America](https://www.riaa.com/reports/riaa-2015-year-end-sales-shipments-data-report-riaa/) (RIAA)
  reports Market Size for 2015 at $4.95B
* Digital Format is 71.2% of market size at $3.52B

### Digital Sales
* Singles: 1.021B --> $1.227B
* Albums: 0.109B --> $1.090B
* Video: 0.003B --> $0.006B

### Subscriptions
* Subscriptions:  0.011B --> $1.220B
* Sound Exchanges:  $0.803B
* Demand Streaming:  $0.385B

### Synchronization Royalties
* $0.203B

---

## Competitive Landscape of Recording Labels

### Big Three Recording Labels
* Table shows percentage of global record label revenue and revenue for the 
Big Three Recording Labels

Recording Label | % Global Recording Revenue (2016)^1 | Global Recording Revenue^2
---|---|---
Universal | 28.9% | $5.57B
Sony | 22.4% | $4.32B^3
Warner | 17.4% | $3.35^3
Independents | 31.3% | $6.03^3

1.  GLOBAL MARKET SHARES 2016: SONY AND WARNER GAIN ON UNIVERSAL, AS INDIES RULE
[Music Business Worldwide](http://www.musicbusinessworldwide.com/global-market-shares-2016-sony-and-warner-gain-on-universal-as-indies-rule/)
2. Universal Music 2016 Earnings: Streaming Drove Revenue Growth for Recordings,
Publishing, [Billboard](http://www.billboard.com/articles/business/7701980/universal-music-group-2016-earnings-streaming)
3. Estimated from the firm's % Global Recording Revenue and Universal's Global Recording Revenue

---

## Competitive Landscape of Recording Labels

Dominant |  Independent  |   Labels^1
---|---|---
ATO Records | Big Machine | Broken Bow Records
Concord | CURB | Disney
Hollywood |Buena | Epitaph
Glassnote  | Razor & Tie | Wind Up

Separately, [List](http://www.hawaiianmusichistory.com/recordings/record-companies.htm) of 
Hawaiian Music Record Companies

1. IFPI Recording Industry in Numbers 2012

---

## Profile of American Music Consumer 2015
* Listeners (91% of Americans) hear an average 24 hours music per week^1
* 61% of listeners are older than 30 yrs^2
* Summary of Annual Music Consumption^1

Item | Total | Teens (13-17) | Millenials (18-34)
---|---|---|---
Amount ($) | $152 | $80 | $163
Live Music Concerts | 32% | 31% | 29%
Music Festivals | 10% | 9% | 17%
Satellite Radio Subscription | 11% | 1% | 5%
Subscription Streaming | 7% | 8% | 9%
Physical Format | 13% | 13% | 9%
Digital Format | 11% | 25% | 12%
Music Gift Cards | 7% | 8% | 3%
Small Live Music Show | 5% | 3% | 7%
DJ Event | 5% | 5% | 11%

1. 2015 Nielsen Music US Report. 2. IFPI Recording Industry in Numbers 2012

---

## Income Profile of Musicians
* Hourly and Annual compensation for Musicians^1

Compensation | Mean | Median
---|---|---
Hourly | $28.91 | $20.07
Annual | $55,561 | $50,000

* Distribution of Hourly Wage for Musicians^2

Percentile | 10% | 25% | 50% (median) | Mean | 75% | 90%
 ---|---|---|---|---|---|---
 Hourly Wage | $9.20 | $13.20 | $24.20 | $33.62 | $44.01 | $68.98
 
* In Oakland-Hayward-Berkeley, CA Metropolitan Division, average hourly wage is 
$48.12 for a population of 440 employees^2

1. Peter C. DiCola, "Money from Music: Survey Evidence on Musicians'
Revenue and Lessons About Copyright Incentives", 55 Arizona Law Review 301
(2013) [link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2199058)
2. Occupational Employment Statistics: Musicians and Singers, BUREAU
LABOR STATS. (2015), [link](http://www.bls.gov/oes/current/oes272042.htm)


---

## Work Profile of Musicians
* Revenue from major sources for Rock, Pop, and other musicians,
but excluding Classical & Jazz musicians, and Composers^1

Composing | Recording | Session Work | Live Perf. | Merchanidse | Salary | Teaching | Other | Total
---|---|---|---|---|---|---|---|---
$3,088 | $2,234 | $4,118 | $8,176 | $588 | $3,235 | $4,412 | $2,029 | $27,970
11% | 8% | 15% | 29% | 2% | 12% | 16% | 7% | 100%

1. Peter C. DiCola, "Money from Music: Survey Evidence on Musicians'
Revenue and Lessons About Copyright Incentives", 55 Arizona Law Review 301
(2013) [link](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=2199058)

---

## Benefits of Streaming Music for Musicians
* Summary of Revenue Stream^1

Stream Type | Royalty per album per user | Artist Share | Songwriter Share
------------|-------------------|--------------|----------------
Average     | $0.21 | $0.03 | $0.02
Subscription| $0.44 | $0.05 | $0.04
Free        | $0.13 | $0.01 | $0.01

* For artist/songwriter, $1k / month revenue stream requires 20k subscribers
* Reach vs Engagement is the new Sales vs Airplay
* Best perspective: marketing campaign that pays for itself
* Some industry analysts are predicting closure of iTunes music sales in
favor of streaming by 2020^2

1. Music Industry Blog, "After The Album: How Playlists Are Re-Defining Listening", April 2016, [link](https://musicindustryblog.wordpress.com/2016/04/26/after-the-album-how-playlists-are-re-defining-listening/)
2. Paul Resnikoff, "Apple Terminating Music Downloads 'Within 2 Years'", Digital Music News, May 2016, [link](http://www.digitalmusicnews.com/2016/05/11/apple-terminating-music-downloads-two-years/)

---

## [Platforms for Distribution of Digital Music](https://en.wikipedia.org/wiki/Comparison_of_online_music_stores)

Store | Track Count [M] | Ownership | Sales (2016) | Fees | Right to Withdraw
------|---|---|---|---|---
[Itunes](https://www.apple.com/itunes/working-itunes/sell-content/music-faq.html) |  43  | Public | | | 
Windows Store | 40 | Public |  | | 
[Google Play Music](play.google.com/artists) | 40 | Public |  | | 
Qobuz | 28 |  | | | 
7digital | 27 | Public | $17.2M | | 
[Amazon Music](https://www.amazon.com/gp/help/customer/display.html?nodeId=14061761) | 20 | Public |  | | 
[Bandcamp](https://bandcamp.com/fair_trade_music_policy) | 18.1 | Private |  | | 
eMusic | 17 |  |  | | 
WiMP | 13 |  |  | | 
GhostTunes | 10 |  |  | | 
mora | 4.4 |  |  | | 
[CDbaby](https://members.cdbaby.com/sell-music) | 3 |  | | 15% | Yes
[Beatport](https://about.beatport.com/contact-us/) | 2 |  | | | 
[Nimbit](http://www.nimbit.com/) | 1 |  | | |

---

## Additional Platforms for Distribution of Digital Music
* Selling: [Bleep](https://bleep.com/faqs),
  [Juno](https://lms.juno.co.uk/lms/login.php),
  [MondoTunes](http://www.mondotunes.com/sell-your-music),
  [Traxsource](http://support.traxsource.com/article/how-can-i-sell-my-music-on-traxsource),
  [Whatpeopleplay](https://www.whatpeopleplay.com)
* Streaming:   [Soundcloud](https://on.soundcloud.com/about), 
  [Mixcloud](https://www.mixcloud.com/about/)
* [Listing of digital platforms](http://whymusicmatters.com/find-music) recognized by RIAA
* [Listing of digital platforms](http://www.pro-music.org/legal-music-services-north-america.php) recognized by artists, labels, & publishers

---

## New Disrupting Platform

### [Distrokid](https://distrokid.com/) changes pricing for distributing music to aggregating stores, e.g. iTunes, Amazon Music, etc

* Existing Competitor Pricing Model:  per track or per album fees with revenue sharing
* New Pricing Model:  Low annual subscription fee with unlimited uploads & no revenue sharing $\Longrightarrow$ more earned income goes directly to artist

---

## Summary

* Live performance is dominant revenue stream for musicians excluding
composers, classical, and jazz musicians
* Recorded music is less than 1/3 of total revenue stream for musicians excluding
composers, classical, and jazz musicians
* Bandcamp may be best platform for direct digital music sales by an
independent musician without strong label backing
* Distrokid may be best platform for digital music distribution to aggregating
stores, e.g. Itunes, Amazon Music, etc
* A strategic plan for independent musicians is shown in following 7 slides

---

## Strategic Plan:  Guerilla Sales & Touring (1/7)

### Primary Assumptions of Musician / Artist
* Releasing track / album
* Live performance tour is planned (arbitrarily restricted to California)
* [Tour cities]( ./assets/img/tourTbl.PNG) have either
[University of California](https://en.wikipedia.org/wiki/University_of_California)
and / or
[California State University](https://en.wikipedia.org/wiki/California_State_University#cite_note-calstate.edu-73)
campus
* Minimal budget for touring by artist
* Fans have low to moderate interest or have low discretionary funds
* Musician / Artist expects profit
* Travel costs estimated by
[IRS](https://www.irs.gov/tax-professionals/standard-mileage-rates/) for mileage
and [FederalPay.org](https://www.federalpay.org/perdiem/2017/california) for 
meals and lodging

---

## Strategic Plan:  Guerilla Sales & Touring (2/7)

### Revenue Model for Guerrilla Tour:  50% margin
* Appearances hosted by venue with revenue sharing
* Venue keeps bar / concession
* Musician / Artist keeps door and merchandising
* Entry:  $20
* Average dollar cost per city based on per diem & milage is $212 \pm 54$
* Assuming 266 dollar cost & 50% margin, Door $\geq$ $532 implies Head Count 27^+
* Based on 8 hour day, wage equivalent is $33.25 per hour for musician / artist
* Low cost and low head count for Guerrilla Tour enables weekday events
$\Longrightarrow$ reduces
tour complexity

---

## Strategic Plan:  Guerilla Sales & Touring (3/7)

### Key Elements & Timeline of Business Plan
1. Market Outreach
2. Release Track / Album
3. Market Outreach 
4. Execute Tour 
5. Continue Market Outreach until Track / Album Sales decay to 20% of peak sales

### Key Resources for Business Plan
* Market Outreach on Social Media:  Facebook, Twitter, YouTube, BandsinTown,
BandCamp, and MixCloud
* Direct digital sales through BandCamp
* Digital distribution through Distrokid
* Optional:  Large white vinyl window decal on tour vehicle with URL to BandCamp

---

## Strategic Plan:  Guerilla Sales & Touring (4/7)

### Establish Digital Music Presence (Revenue)

1. Establish either label or artist presence on 
[Bandcamp](https://bandcamp.com/fair_trade_music_policy) for direct sales and for 
creating digital download codes
2. Establish distribution account on [Distrokid](https://distrokid.com/) for 
distribution of digital music

### Establish Social Media Presence (Marketing)
1. Establish presence on [Facebook](https://www.facebook.com) that develops intimacy
with fans (minimally two photos per week & consider FB Live for <30s video clip,
but video should release through YouTube)
2. Establish presence on [Twitter](https://www.twitter.com) that keeps fans informed
about appearances, sprinkles in humorous observations, and URLs to digital sales
3. Establish presence on [Youtube](https://www.youtube.com) to share short (<60s)
video clips to Facebook and / or Twitter
4. Establish presence on [MixCloud](https://www.mixcould.com) to share extended 
sets (SoundCloud limits time $\leq$ 3 hr; else, pay-wall)
5. Use [URL Shortener](https://goo.gl/) to reduce URL length for Twitter character
limit

---

## Strategic Plan:  Guerilla Sales & Touring (5/7)

### Merchandising

1.  T-shirts:  must sell for $20^+ with 50% margin
2. Generate 4 pg CD jacket that enables digital downloads, but sells at cost of 
physical CD

* Front page - Musician portrait or cover art
* Inside left page - Intentionally blank for autograph by artist
* Inside right page - digital download code that enables single-use download of single 
track or album, track list, and / or additional artwork or image 
* Back page - Additional artwork, credits, and / or legal disclosures
* Package CD jacket in cellophane wrapper
* COMMENT: format enables music sales, but less cumbersome than actual CDs



---

## Strategic Plan:  Guerilla Sales & Touring (6/7)

###  Direct Marketing for Venues
1. Generate full page cut-sheet that markets musician / artist for 
review by venue's booking agent

* Include links to Social Media
* Report engagement statistics from Social Media
* Include link to $\leq$ 60s video clip of performance
* Host same page on website

---

## Strategic Plan:  Guerilla Sales & Touring (7/7)

### OPTIONAL:  develop resource network for guerrilla touring

1. Identify fans in target tour cities that will support you by:

* Making contact with target venue and close booking using cut-sheet
* Hosting you while making appearance in their city
* Assisting with supporting door & and merchandising sales
* Reimbursement:  the experience and complimentary entry + 1

---

## Final Conclusions

* Guerrilla Sales & Touring provides revenue consistent with measured income 
profile of musicians
* Guerrilla Sales & Touring reduces complexity by enabling use of small clubs
and small attendance head counts
* Available digital sales and digital distribution platforms enable track / 
album sales with low margin $\Longrightarrow$ greater revenue to muscian
* Available social media enables low cost marketing outreach to fanbase

## Survey 
* Please click the [Link](https://goo.gl/forms/hfLuFQSti5xIxs8J2) to our survey
that is hosted on Google
* Your survey responses help improve this presentation for us